export const shopTypes = {
    SHOP_DATA:'Shop_Data',
    FETCH_COLLECTION_START:'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS:'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILURE:'FETCH_COLLECTION_FAILURE'
}